### PR TITLE
Added an effect size estimate (Cohen's f2) to niak_glm. 

### PR DESCRIPTION
**Pull request by pbellec**
This should fix issue #148

### CODE REVIEW

**Comment by poquirion** [comment]
@pbellec for fp_regress_confounds_subject1_session1_motor error:
C (contrast) is never set in bricks/fmri_preprocess/niak_brick_regress_confounds.m so when it calls niak_glm.m, it crashes.

**Comment by poquirion** [comment]
And in fact its the same thing everywhere. The c value is not needed/provided when OPT.TEST is none, and should not be computed. Now it is computes.

**Comment by poquirion** [comment]
The two failling test have the same origin and are due to a new "f2" matrix added to glm results.

I will merge the pull request for the new release.

**Comment by pbellec** [comment]
I have re-created an #issue148 branch. First there was a problem in the formula used to compute f2, which I have fixed on the branch. Also, I have added F2 maps (with and without FDR threshold) to the outputs of the GLM connectome pipeline. The XX_fdr maps have been renamed XX_ttest_fdr for consistency with the XX_f2_fdr maps.

**Pull request merged**
