### PR TITLE
Added support for intra-network connectivity in the connectome pipeli…

### PR DESCRIPTION
**Pull request by pbellec**
…ne. Should fix issue #228.

### CODE REVIEW

**Comment by pbellec** [comment]
I have changed the output format of the connectome pipeline, to include within-network connectivity. This means the tests are going to fail. I will review the differences between the old and new pipelines, and if everything is ok we will need a new target for tests.

**Comment by pbellec** [comment]
So I went through the details of the logs. The reason why the test fails is that I added intra-network connectivity to the connectome pipeline. All other measures remain unchanged (using default parameters). However, I did observe small variations (from 10^-15 to 10^-3, depending on the metric), and I don't know where they came from. I guess it is a reflection of the difference between my ubuntu box and the environment where the target was built.

**Comment by pbellec** [comment]
The travis build exactly reproduces what I have on my machine. So there may be a subtle difference in implementation that I missed. I will need to investigate more :/

**Comment by pbellec** [comment]
OK so I finally got it. Thanks to our test pipelines I found an inconsistency between the old and new ways of binarizing graphs. It's fixed. I also by mistake fixed other unrelated issues on that branch, will have to do with it. So there is now an auto animation in the preprocess QC reports, as well as a red outline for important anatomical landmarks.

**Comment by pbellec** [comment]
OK so the latest revision exactly matches previous NIAK results, except the connectome pipeline now offers metrics for intra-network connectivity. @poquirion it is ready to be merged in master, but it will take an new target.

**Comment by pbellec** [comment]
This PR fixes issues #230 #228 #231

**Comment by poquirion** [comment]
I am releasing a new target

**Pull request merged**
